// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfr66IAPmGf-vSr1hc-HPBFX3ToMl0J3Y',
    appId: '1:1098292286785:web:4e227e1846b6fe6c4bbdc0',
    messagingSenderId: '1098292286785',
    projectId: 'flashchat-5abaf',
    authDomain: 'flashchat-5abaf.firebaseapp.com',
    storageBucket: 'flashchat-5abaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuN_x_Z4VFAUAmUqjZtjAWwg6xsCON5c4',
    appId: '1:1098292286785:android:b32921a3682b9ad74bbdc0',
    messagingSenderId: '1098292286785',
    projectId: 'flashchat-5abaf',
    storageBucket: 'flashchat-5abaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCej2Ggm2awDN4jXdiqLclwq2NKkmtSVis',
    appId: '1:1098292286785:ios:36d54d25af81814d4bbdc0',
    messagingSenderId: '1098292286785',
    projectId: 'flashchat-5abaf',
    storageBucket: 'flashchat-5abaf.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCej2Ggm2awDN4jXdiqLclwq2NKkmtSVis',
    appId: '1:1098292286785:ios:17428a5c954f60a54bbdc0',
    messagingSenderId: '1098292286785',
    projectId: 'flashchat-5abaf',
    storageBucket: 'flashchat-5abaf.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
